// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDadQjNHjHk9nrJSyd83JS-ur4XQ8GaaXQ',
    appId: '1:176175791521:web:a1b49737b4d7f36a60dfe0',
    messagingSenderId: '176175791521',
    projectId: 'gp-695a5',
    authDomain: 'gp-695a5.firebaseapp.com',
    storageBucket: 'gp-695a5.appspot.com',
    measurementId: 'G-9KY0RQ17SV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd2S485yBya9Y6TY5JvRPcomMsnY_Txnc',
    appId: '1:176175791521:android:690c76abd7a521e860dfe0',
    messagingSenderId: '176175791521',
    projectId: 'gp-695a5',
    storageBucket: 'gp-695a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChICu1jQq6EpZpgDNtUfSDxGLt59lLe7g',
    appId: '1:176175791521:ios:01acadeca76dd22a60dfe0',
    messagingSenderId: '176175791521',
    projectId: 'gp-695a5',
    storageBucket: 'gp-695a5.appspot.com',
    iosClientId: '176175791521-2sgf6vn1ua9oh6honciodatdqk6lodig.apps.googleusercontent.com',
    iosBundleId: 'com.example.circlight',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChICu1jQq6EpZpgDNtUfSDxGLt59lLe7g',
    appId: '1:176175791521:ios:01acadeca76dd22a60dfe0',
    messagingSenderId: '176175791521',
    projectId: 'gp-695a5',
    storageBucket: 'gp-695a5.appspot.com',
    iosClientId: '176175791521-2sgf6vn1ua9oh6honciodatdqk6lodig.apps.googleusercontent.com',
    iosBundleId: 'com.example.circlight',
  );
}
